RedHat-Middleware-Workshops/dayinthelife-integration

.gitignore
support/install/ansible/playbooks/openshift/install.retry

Small change -- just ignoring Ansible retry files as is best practice

Ignore retry

---

projects/location-soap/src/main/resources/schema.sql

@btierney Would you mind taking a look? This is causing an issue for me

Fix drop table instruction on location_detail table

---

support/install/ansible/playbooks/openshift/roles/provision_gogs/defaults/main.yml
support/install/ansible/playbooks/openshift/roles/provision_gogs/tasks/main.yml
support/install/ansible/playbooks/openshift/roles/provision_gogs/tasks/wait-for-deployment.yml

fixes #212 
How to test it: Run the install playbook or create one as below:
```
ansible-playbook  -i myinv -e "ocp_apps_domain=$(minishift ip).nip.io" -e 'usersno=5' -e 'configure_only=false' -e 'gogs=true' -e 'create_realms=true' install-gogs.yml
```
```
---
- name: "Install gogs Workshop"
hosts: local
connection: local
tasks:
- import_role:
name: provision_gogs
when: gogs
```

gogs fixes

---

docs/labs/citizen-integrator-track/lab01/README.md
docs/labs/citizen-integrator-track/lab02/README.md
docs/labs/citizen-integrator-track/lab03/README.md
docs/labs/citizen-integrator-track/lab04/README.md
docs/labs/citizen-integrator-track/lab05/README.md
docs/labs/citizen-integrator-track/lab06/README.md
docs/labs/citizen-integrator-track/lab06/support/homepage.example
docs/labs/citizen-integrator-track/lab07/README.md
docs/labs/developer-track/lab01/README.md
docs/labs/developer-track/lab02/README.md
docs/labs/developer-track/lab03/README.md
docs/labs/developer-track/lab04/README.md
docs/labs/developer-track/lab05/README.md
docs/labs/developer-track/lab06/README.md
docs/labs/developer-track/lab07/README.md
docs/labs/developer-track/lab07/support/homepage.example
docs/labs/developer-track/lab08/README.md

Use this branch if using the dil1.opentry.me cluster.

dil1 branch

---

docs/labs/citizen-integrator-track/lab01/README.md
docs/labs/citizen-integrator-track/lab02/README.md
docs/labs/citizen-integrator-track/lab03/README.md
docs/labs/citizen-integrator-track/lab04/README.md
docs/labs/citizen-integrator-track/lab05/README.md
docs/labs/citizen-integrator-track/lab06/README.md
docs/labs/citizen-integrator-track/lab06/support/homepage.example
docs/labs/citizen-integrator-track/lab07/README.md
docs/labs/developer-track/lab01/README.md
docs/labs/developer-track/lab02/README.md
docs/labs/developer-track/lab03/README.md
docs/labs/developer-track/lab04/README.md
docs/labs/developer-track/lab05/README.md
docs/labs/developer-track/lab06/README.md
docs/labs/developer-track/lab07/README.md
docs/labs/developer-track/lab07/support/homepage.example
docs/labs/developer-track/lab08/README.md

Reverts RedHatWorkshops/dayinthelife-integration#227

Revert "dil1 branch"

---

support/install/ansible/playbooks/openshift/roles/provision_apicurio/tasks/main.yml
support/install/ansible/playbooks/openshift/roles/provision_backend/tasks/main.yml
support/install/ansible/playbooks/openshift/roles/provision_threescale/defaults/main.yml
support/install/ansible/playbooks/openshift/roles/provision_threescale/tasks/create-service.yml
support/install/ansible/playbooks/openshift/roles/provision_threescale/tasks/create-tenants.yml
support/install/ansible/playbooks/openshift/roles/provision_threescale/tasks/main.yml

Fixes several errors when running the integreatly playbook 2 or more times.
Verification:
Run the installer 2 or more times against a integreatly workshop (1.0.3).
ping @aidenkeating @maleck13

playbook run fixes

---

support/install/ansible/playbooks/openshift/roles/provision_apicurio/tasks/main.yml
support/install/ansible/playbooks/openshift/roles/provision_backend/tasks/main.yml
support/install/ansible/playbooks/openshift/roles/provision_threescale/defaults/main.yml
support/install/ansible/playbooks/openshift/roles/provision_threescale/tasks/create-service.yml
support/install/ansible/playbooks/openshift/roles/provision_threescale/tasks/create-tenants.yml
support/install/ansible/playbooks/openshift/roles/provision_threescale/tasks/main.yml

Reverts RedHatWorkshops/dayinthelife-integration#230 
Having error when running 
TASK [provision_threescale : Get SSO Token Longer Lifespan] *****************************************************************************************************************************
FAILED - RETRYING: Get SSO Token Longer Lifespan (10 retries left).
FAILED - RETRYING: Get SSO Token Longer Lifespan (9 retries left).
FAILED - RETRYING: Get SSO Token Longer Lifespan (8 retries left).
FAILED - RETRYING: Get SSO Token Longer Lifespan (7 retries left).
FAILED - RETRYING: Get SSO Token Longer Lifespan (6 retries left).
FAILED - RETRYING: Get SSO Token Longer Lifespan (5 retries left).
FAILED - RETRYING: Get SSO Token Longer Lifespan (4 retries left).
FAILED - RETRYING: Get SSO Token Longer Lifespan (3 retries …

Revert "playbook run fixes"

---

README.md

Adding RHPDS installation notes.
fixes #218 
ping  @aidenkeating  @hguerrero

RHDPS installation notes

---

README.md
support/install/RHPDSInstallation.md

Moving it under install and also update user realm instructions

RHPDS Installation Script

---

docs/labs/developer-track/lab04/README.md

This PR is for the following issue: -#247

added common gotcha to lab4 step 2.6

---

docs/labs/developer-track/lab06/README.md

This PR is for the following issue: -#251

added common gotcha for build fail due to SSO Location API

---

projects/threescale-automate/src/main/java/com/redhat/CamelRoutes.java
support/install/ansible/playbooks/openshift/integreatly.yml
support/install/ansible/playbooks/openshift/roles/provision_microcks/tasks/main.yml
support/templates/microcks-template.yml

The following should fix issues
https://github.com/RedHatWorkshops/dayinthelife-integration/issues/264
https://github.com/RedHatWorkshops/dayinthelife-integration/issues/266
**Note**
Not currently tested. Not sure how to test issue 266
Will uninstall and reinstall to test issue 264

Issue 264 and 266 keycloak url issues

---

support/install/RHPDSInstallation.md

Fix some typos

---

docs/labs/developer-track/lab01/README.md

Fixing typo

---

support/install/RHPDSInstallation.md

Update to clone the V2 branch of the installer repo

Update to clone V2 branch

---

docs/labs/developer-track/lab01/README.md
support/install/RHPDSInstallation.md

Closes RedHatWorkshops/dayinthelife-integration#269
Closes RedHatWorkshops/dayinthelife-integration#298

fixes to RHPDS installs

---

docs/labs/developer-track/lab03/walkthrough.adoc

Task 3 - Catalogue is named Service catalogue now it seems and it can be found in the top menu.
Also did some clarification on chosen project in the popup when adding the database.
These changes comes from a workshop where attendants had some problems regarding this.

Minor adjustments on Dev Track - Lab 3

---

docs/labs/developer-track/lab05/walkthrough.adoc

link to 3scale  is not correct.  change it to "https://www.3scale.net/

fix wrong link

---

docs/labs/citizen-integrator-track/lab07/walkthrough.adoc
docs/labs/developer-track/lab06/walkthrough.adoc
docs/labs/developer-track/lab07/walkthrough.adoc

Fixes for a few of the things noticed during the Agile Integration workshop held at Miracle A/S.

Added hint for self-signed certificate and corrected image syntax

---

docs/labs/citizen-integrator-track/lab03/walkthrough.adoc
docs/labs/citizen-integrator-track/lab04/walkthrough.adoc
docs/labs/developer-track/lab02/walkthrough.adoc
docs/labs/developer-track/lab03/walkthrough.adoc

Fixed some issues with URLs and instructions order in the labs.

Fixed instruction issues.

---

docs/labs/citizen-integrator-track/lab01/walkthrough.adoc
docs/labs/citizen-integrator-track/lab03/walkthrough.adoc
docs/labs/citizen-integrator-track/lab04/walkthrough.adoc
docs/labs/citizen-integrator-track/lab06/walkthrough.adoc
docs/labs/citizen-integrator-track/lab07/walkthrough.adoc
docs/labs/developer-track/lab01/walkthrough.adoc
docs/labs/developer-track/lab02/walkthrough.adoc
docs/labs/developer-track/lab03/walkthrough.adoc
docs/labs/developer-track/lab04/walkthrough.adoc
docs/labs/developer-track/lab07/walkthrough.adoc
docs/labs/operations-track/10-setup-jenkins-pipelines.md

Minor edits after walking through both tracks.

Resolve typos, formatting issues, and instruction clarity.
